### ISSUE TITLE
[Bug] context deadline exceeded for hello-world due to usage of too-old version of SDK

### ISSUE THREAD

**Issue by aybabtme** [temporalio/money-transfer-project-template-go#10]
### What are you really trying to do?

Running the getting started flow with this repo doesn't work with latest docker-compose, with workers continually returning and logging `context.ErrDeadline`. Updating the SDK to something later than v1.0.0 seems to fix the problem.

### Describe the bug

It seems like the latest stack deployed in your docker-compose repo has new expectations about `scheduleToCloseTimeout` not being sent (being nil) or having a non-zero value. When running your getting started exercises, right now the code doesn't seem to send a value for `scheduleToCloseTimeout`, or at least it seems to be given a non-nil value when running `go run start/main.go`. Subsequently, the JSON for the activity, in the UI, shows that the value is non-nil but of `0s`.

```json
      "scheduleToCloseTimeout": {
        "duration": 0
      },
```

An the worker code, using SDK v1.0.0, pulls this task and interprets this as a 0s timeout. Hence every attempt at executing the task ends up with an error for the context being already timed out.

### Minimal Reproduction

Checkout the latest `docker-compose` and the latest version of this repo and try to run it. Executing the worker will result in:

```
2022/04/17 11:03:45 INFO  Task processing failed with client side error Namespace default TaskQueue TRANSFER_MONEY_TASK_QUEUE WorkerID 84696@Antoines-MacBook-Pro.local@ WorkerType ActivityWorker Error context deadline exceeded
```

### Environment/Versions

- OS and processor: Intel Mac
- Temporal Version: latest docker compose, latest checkout of this repo
- Are you using Docker or Kubernetes or building Temporal from source? docker-compose

**Comment by antempus** [comment]
I am also encountering this issue

**Comment by yiminc** [comment]
This is fixed now.
