### ISSUE TITLE
fatal: git fetch-pack: expected shallow list

### ISSUE THREAD

**Issue by pguerin3** [temporalio/money-transfer-project-template-go#3]
**Describe the bug**
I'm running Docker on a Linux VM (in VirtualBox using Vagrant) on a Windows 10 host.
So I installed Temporal, and got the server running without problems.
Also there are no problems running the GUI via localhost:8088 as I have forwarded the port to 8088 on the host.
I can see the GUI in the browser on my Windows host.

The problem starts when I try to run the tutorial: money-transfer-project-template-go
I get the following error:
```
[vagrant@ol7-vagrant money-transfer-project-template-go]$ go run start/main.go
go: go.temporal.io/sdk@v1.0.0 requires
        go.temporal.io/api@v1.0.0 requires
        google.golang.org/genproto@v0.0.0-20200925023002-c2d885f95484 requires
        google.golang.org/grpc@v1.27.0 requires
        github.com/envoyproxy/go-control-plane@v0.9.1-0.20191026205805-5f8ba28d4473: invalid version: git fetch --unshallow -f origin in /home/vagrant/go/pkg/mod/cache/vcs/f80b47a3f3002be1a2e7f6fd3f347122d409513e6beb38652769fd9ce11d1634: exit status 128:
        fatal: git fetch-pack: expected shallow list
[vagrant@ol7-vagrant money-transfer-project-template-go]$
```

**Versions (please complete the following information where relevant):**
 - OS:
```
Microsoft Windows 10.0.19042
Oracle Virtualbox Version 6.1.22 r144080 (Qt5.6.2)
Linux ol7-vagrant 5.4.17-2102.202.5.el7uek.x86_64
```
Temporal Version is the latest as downloaded from last week
I am using Docker:
```
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
go version go1.15.5 linux/amd64
```

**Comment by sriramNV** [comment]
try installing the updated go version or downgrade to v1.14 or try here -> "https://github.com/golang/go/issues/38373"

**Comment by pguerin3** [comment]
I upgraded my go installation from 1.15.5 to 1.16 and the example works now.
I used the following procedure for the upgrade: https://golang.org/doc/install
